services:
  postgre:
    image: postgres
    container_name: cqrs_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cqrs_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
  postgre_test:
    image: postgres
    container_name: cqrs_test_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cqrs_test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
